/* III-FOUNDERS-ANCHOR — implementation. */
#include "iii/founders_anchor.h"
#include <stdlib.h>
#include <string.h>

extern void iii_sha256(const void *data, size_t len, uint8_t out[32]);

/* Ed25519 from CRYPTO-AGILITY (RFC 8032). */
extern void iii_ed25519_keygen(uint8_t pk[32], const uint8_t seed[32]);
extern void iii_ed25519_sign  (uint8_t sig[64],
                               const uint8_t *msg, size_t msglen,
                               const uint8_t pk[32], const uint8_t seed[32]);
extern int  iii_ed25519_verify(const uint8_t sig[64],
                               const uint8_t *msg, size_t msglen,
                               const uint8_t pk[32]);

/* Phase XII-zeta Omega12 Founders-Anchor public key: generated by the real
 * ceremony (gen_anchor_seed -> §4.7 HW-entropy DRBG 64-byte seed -> SHA-256 ->
 * ed25519_keypair_from_seed).  The matching private seed is sealed off-repo
 * (operator-held, per ADR); only this public key is committed.  Verified by a
 * sign+verify round-trip with the derived key.  Replaces the 0xCC placeholder. */
const uint8_t III_FOUNDERS_ANCHOR_PUBLIC_KEY_DEFAULT[32] = {
    0x20,0xbd,0xf0,0xd4, 0x16,0xce,0x03,0x5a,
    0xcb,0x57,0x34,0x92, 0x3e,0x82,0x20,0x21,
    0x0c,0x6b,0x05,0x96, 0x19,0x22,0xfc,0xd4,
    0xb0,0x52,0x83,0x1b, 0xb1,0xd0,0xc2,0x1d
};

const char *iii_anchor_authority_name(iii_anchor_authority_t a) {
    switch (a) {
        case III_AA_TIER3_VETO:        return "tier3-veto";
        case III_AA_DRTM_RESET:        return "drtm-reset";
        case III_AA_PFS_DENY_QUOTE:    return "pfs-deny-quote";
        case III_AA_SUITE_SWAP_COSIGN: return "suite-swap-cosign";
        case III_AA_WITNESS_INJECT:    return "witness-inject";
        case III_AA_CATALYST_HALT:     return "catalyst-halt";
        case III_AA_REVOKE_PROMOTION:  return "revoke-promotion";
        default:                       return "none";
    }
}

const char *iii_anchor_amend_status_name(iii_anchor_amend_status_t s) {
    switch (s) {
        case III_AMEND_OK:                       return "ok";
        case III_AMEND_REJECT_NO_QUORUM:         return "reject-no-quorum";
        case III_AMEND_REJECT_FNDR_VETO_MISSING: return "FNDR-VETO-MISSING";
        case III_AMEND_REJECT_INVALID:           return "reject-invalid";
        default:                                 return "unknown";
    }
}

void iii_anchor_compute_fingerprint(const uint8_t public_key[32], uint8_t out[32]) {
    if (!public_key || !out) return;
    iii_sha256(public_key, 32, out);
}

/* ----------------------------------------------------------------------------
 * Sign / verify — RFC 8032 Ed25519.  The 64-byte iii_anchor_signature_t holds
 * the (R, S) pair directly.  The "secret_key" parameter is the 32-byte Ed25519
 * seed (sk), from which the public key and signing scalar are derived. */

void iii_anchor_sign(const uint8_t          public_key[32],
                     const uint8_t          secret_key[32],
                     const uint8_t         *directive,
                     size_t                 directive_len,
                     iii_anchor_signature_t *out)
{
    if (!out) return;
    memset(out, 0, sizeof(*out));
    if (!public_key || !secret_key) return;
    iii_ed25519_sign(out->bytes, directive, directive_len, public_key, secret_key);
}

bool iii_anchor_verify(const uint8_t                public_key[32],
                       const uint8_t               *directive,
                       size_t                       directive_len,
                       const iii_anchor_signature_t *sig)
{
    if (!public_key || !sig) return false;
    return iii_ed25519_verify(sig->bytes, directive, directive_len, public_key) == 0;
}

/* ----------------------------------------------------------------------------
 * Shamir Secret Sharing over GF(2^8) — direct AES-poly multiplication.
 * Reducing polynomial: x^8 + x^4 + x^3 + x + 1 (0x11B).
 * ---------------------------------------------------------------------------- */

static uint8_t gf_mul(uint8_t a, uint8_t b) {
    uint8_t r = 0;
    for (unsigned i = 0; i < 8; ++i) {
        if (b & 1u) r ^= a;
        uint8_t hi = (uint8_t)(a & 0x80u);
        a = (uint8_t)(a << 1);
        if (hi) a ^= 0x1Bu;
        b = (uint8_t)(b >> 1);
    }
    return r;
}

static uint8_t gf_inv(uint8_t a) {
    if (a == 0) return 0;
    /* a^(-1) = a^254 by Fermat's little theorem in GF(2^8). */
    uint8_t r = 1;
    uint8_t base = a;
    uint8_t exp = 254;
    while (exp) {
        if (exp & 1u) r = gf_mul(r, base);
        base = gf_mul(base, base);
        exp = (uint8_t)(exp >> 1);
    }
    return r;
}

static uint8_t gf_add(uint8_t a, uint8_t b) { return (uint8_t)(a ^ b); }

bool iii_anchor_shamir_split(const uint8_t       secret[32],
                             unsigned             total_shares,
                             unsigned             threshold,
                             iii_anchor_share_t  *shares,
                             unsigned             max_shares)
{
    if (!secret || !shares) return false;
    if (threshold == 0 || threshold > total_shares) return false;
    if (total_shares > max_shares || total_shares > 16) return false;

    /* For each byte of the secret, build a polynomial of degree (threshold - 1)
     * with secret as constant term and pseudo-random coefficients. */
    /* Pseudo-random coefficients: deterministic from secret + seed. */
    for (unsigned s = 0; s < total_shares; ++s) {
        shares[s].share_index = (uint8_t)(s + 1u);
    }
    for (unsigned b = 0; b < 32; ++b) {
        uint8_t coeffs[16];
        coeffs[0] = secret[b];
        for (unsigned i = 1; i < threshold; ++i) {
            uint8_t mix[34];
            memcpy(mix, secret, 32);
            mix[32] = (uint8_t)i;
            mix[33] = (uint8_t)b;
            uint8_t h[32];
            iii_sha256(mix, sizeof(mix), h);
            coeffs[i] = h[0];
        }
        for (unsigned s = 0; s < total_shares; ++s) {
            uint8_t x = (uint8_t)(s + 1u);
            uint8_t y = coeffs[threshold - 1u];
            for (int i = (int)threshold - 2; i >= 0; --i) {
                y = gf_add(gf_mul(y, x), coeffs[i]);
            }
            shares[s].share_bytes[b] = y;
        }
    }
    return true;
}

bool iii_anchor_shamir_reconstruct(const iii_anchor_share_t *shares,
                                   unsigned                  count,
                                   uint8_t                   secret[32])
{
    if (!shares || !secret || count == 0 || count > 16) return false;

    for (unsigned b = 0; b < 32; ++b) {
        uint8_t result = 0;
        for (unsigned i = 0; i < count; ++i) {
            uint8_t numerator = 1, denominator = 1;
            for (unsigned j = 0; j < count; ++j) {
                if (i == j) continue;
                numerator   = gf_mul(numerator,   shares[j].share_index);
                denominator = gf_mul(denominator, gf_add(shares[i].share_index, shares[j].share_index));
            }
            uint8_t inv = gf_inv(denominator);
            if (denominator == 0) return false;
            uint8_t lagrange = gf_mul(numerator, inv);
            result = gf_add(result, gf_mul(shares[i].share_bytes[b], lagrange));
        }
        secret[b] = result;
    }
    return true;
}

/* ----------------------------------------------------------------------------
 * Authority verifications: each takes a directive, signs/verifies via the
 * Anchor.
 * ---------------------------------------------------------------------------- */

static void build_directive(const char   *prefix,
                            size_t         prefix_len,
                            const uint8_t *body,
                            size_t         body_len,
                            uint8_t       *out,
                            size_t        *out_len)
{
    memcpy(out, prefix, prefix_len);
    if (body && body_len) memcpy(out + prefix_len, body, body_len);
    *out_len = prefix_len + body_len;
}

iii_anchor_amend_status_t iii_anchor_amend_apply(const iii_anchor_identity_t *anchor,
                                                  const iii_anchor_amendment_t *amend)
{
    if (!anchor || !amend) return III_AMEND_REJECT_INVALID;
    if (!amend->federation_unanimous) return III_AMEND_REJECT_NO_QUORUM;
    /* Verify Anchor cosignature on the amendment body. */
    uint8_t directive[64];
    memcpy(directive,    amend->target_mhash,    32);
    memcpy(directive+32, amend->new_value_mhash, 32);
    if (!iii_anchor_verify(anchor->public_key, directive, sizeof(directive), &amend->anchor_signature)) {
        return III_AMEND_REJECT_FNDR_VETO_MISSING;
    }
    return III_AMEND_OK;
}

bool iii_anchor_drtm_reset_verify(const iii_anchor_identity_t *anchor,
                                  const iii_anchor_drtm_reset_t *reset)
{
    if (!anchor || !reset) return false;
    uint8_t directive[26 + 32 + 8 + 4];
    size_t  d_len = 0;
    build_directive("III-FOUNDERS-DRTM-RESET-V1", 26, reset->nonce, 32, directive, &d_len);
    for (unsigned i = 0; i < 8; ++i) directive[d_len + i] = (uint8_t)(reset->timestamp >> (i*8));
    d_len += 8;
    for (unsigned i = 0; i < 4; ++i) directive[d_len + i] = (uint8_t)(reset->reason_code >> (i*8));
    d_len += 4;
    return iii_anchor_verify(anchor->public_key, directive, d_len, &reset->signature);
}

bool iii_anchor_pfs_deny_verify(const iii_anchor_identity_t *anchor,
                                const iii_anchor_pfs_deny_t *deny)
{
    if (!anchor || !deny) return false;
    uint8_t directive[24 + 1 + 8 + 1];
    memcpy(directive, "III-FOUNDERS-PFS-DENY-V1", 24);
    directive[24] = (uint8_t)deny->target_kind;
    for (unsigned i = 0; i < 8; ++i) directive[25 + i] = (uint8_t)(deny->target_id >> (i*8));
    directive[33] = (uint8_t)deny->reason;
    return iii_anchor_verify(anchor->public_key, directive, sizeof(directive), &deny->signature);
}

bool iii_anchor_witness_inject_verify(const iii_anchor_identity_t *anchor,
                                      const iii_anchor_witness_inject_t *w)
{
    if (!anchor || !w) return false;
    uint8_t directive[2 + 32 + 8 + 4];
    directive[0] = (uint8_t)(w->cycle_kind);
    directive[1] = (uint8_t)(w->cycle_kind >> 8);
    memcpy(directive + 2, w->payload_mhash, 32);
    for (unsigned i = 0; i < 8; ++i) directive[34 + i] = (uint8_t)(w->timestamp >> (i*8));
    for (unsigned i = 0; i < 4; ++i) directive[42 + i] = (uint8_t)(w->flags     >> (i*8));
    return iii_anchor_verify(anchor->public_key, directive, sizeof(directive), &w->signature);
}

bool iii_anchor_catalyst_halt_verify(const iii_anchor_identity_t *anchor,
                                     const iii_anchor_catalyst_halt_t *halt)
{
    if (!anchor || !halt) return false;
    uint8_t directive[31 + 8];
    memcpy(directive, "III-FOUNDERS-CATALYST-HALT-V1", 29);
    for (unsigned i = 0; i < 8; ++i) directive[29 + i] = (uint8_t)(halt->halt_until >> (i*8));
    return iii_anchor_verify(anchor->public_key, directive, 29 + 8, &halt->signature);
}

bool iii_anchor_revoke_verify(const iii_anchor_identity_t *anchor,
                              const iii_anchor_revoke_t *rev)
{
    if (!anchor || !rev) return false;
    uint8_t directive[24 + 8 + 1];
    memcpy(directive, "III-FOUNDERS-REVOKE-V1", 22);
    for (unsigned i = 0; i < 8; ++i) directive[22 + i] = (uint8_t)(rev->promotion_id >> (i*8));
    directive[30] = (uint8_t)rev->cascade;
    return iii_anchor_verify(anchor->public_key, directive, 22 + 8 + 1, &rev->signature);
}

bool iii_anchor_invariant_holds(const iii_anchor_invariant_check_t *c) {
    if (!c) return false;
    return !(c->attempts_modify_pubkey ||
             c->attempts_modify_fingerprint ||
             c->attempts_remove_amend_apply_anchor_requirement ||
             c->attempts_disable_pfk_anchor_invariant ||
             c->attempts_synthesize_substitute_anchor);
}

/* ----------------------------------------------------------------------------
 * Runtime
 * ---------------------------------------------------------------------------- */
struct iii_anchor_runtime {
    iii_anchor_identity_t identity;
    bool                  identity_set;
    uint64_t              halt_until;       /* 0 = not halted */
    uint64_t              witness_count;
};

iii_anchor_runtime_t *iii_anchor_runtime_create(const iii_anchor_identity_t *anchor) {
    iii_anchor_runtime_t *rt = (iii_anchor_runtime_t *)calloc(1, sizeof(*rt));
    if (!rt) return NULL;
    if (anchor) {
        rt->identity = *anchor;
        rt->identity_set = true;
    } else {
        memcpy(rt->identity.public_key, III_FOUNDERS_ANCHOR_PUBLIC_KEY_DEFAULT, 32);
        iii_anchor_compute_fingerprint(rt->identity.public_key, rt->identity.fingerprint);
        rt->identity.suite_id = 0x0001;
        rt->identity.frozen = true;
        rt->identity_set = true;
    }
    return rt;
}

void iii_anchor_runtime_destroy(iii_anchor_runtime_t *rt) { if (rt) free(rt); }

const iii_anchor_identity_t *iii_anchor_runtime_identity(const iii_anchor_runtime_t *rt) {
    return rt ? &rt->identity : NULL;
}

bool iii_anchor_runtime_is_catalyst_halted(const iii_anchor_runtime_t *rt, uint64_t now) {
    if (!rt) return false;
    if (rt->halt_until == 0) return false;
    if (rt->halt_until == UINT64_MAX) return true;
    return now < rt->halt_until;
}

bool iii_anchor_runtime_apply_halt(iii_anchor_runtime_t *rt,
                                   const iii_anchor_catalyst_halt_t *halt)
{
    if (!rt || !halt) return false;
    if (!iii_anchor_catalyst_halt_verify(&rt->identity, halt)) return false;
    rt->halt_until = halt->halt_until;
    rt->witness_count++;
    return true;
}

bool iii_anchor_runtime_resume(iii_anchor_runtime_t *rt,
                               const iii_anchor_signature_t *resume_sig)
{
    if (!rt || !resume_sig) return false;
    /* Resume directive = "III-FOUNDERS-CATALYST-RESUME-V1" */
    static const char prefix[] = "III-FOUNDERS-CATALYST-RESUME-V1";
    if (!iii_anchor_verify(rt->identity.public_key,
                           (const uint8_t *)prefix, sizeof(prefix) - 1, resume_sig)) {
        return false;
    }
    rt->halt_until = 0;
    rt->witness_count++;
    return true;
}

uint64_t iii_anchor_runtime_witness_count(const iii_anchor_runtime_t *rt) {
    return rt ? rt->witness_count : 0u;
}
