/* iii_ast_kind_name() — stable name table for every AST kind.
 *
 * The table is sparse (gaps in the enum are intentional reserved
 * slots).  We build a fixed-size lookup of size III_AST_KIND_COUNT
 * and return "UNKNOWN" for any value with no entry. */
#include "iii/ast.h"

static const char *NAME_BY_KIND[III_AST_KIND_COUNT] = {0};

static int g_inited = 0;

static void init_table(void) {
    if (g_inited) return;
    g_inited = 1;

    #define X(K) NAME_BY_KIND[(K)] = #K

    /* §4 */
    X(III_AST_MODULE);
    X(III_AST_QUALIFIED_NAME);
    X(III_AST_MODULE_ATTR);
    X(III_AST_IMPORT);
    X(III_AST_IMPORT_ATTR);
    /* §5 */
    X(III_AST_CYCLE_DECL);
    X(III_AST_FORWARD_BLOCK);
    X(III_AST_INVERSE_BLOCK);
    X(III_AST_CYCLE_MODIFIER);
    X(III_AST_FUNCTION_DECL);
    X(III_AST_GENERIC_PARAM);
    X(III_AST_FUNCTION_MODIFIER);
    X(III_AST_PARAM);
    X(III_AST_TYPE_DECL);
    X(III_AST_TYPE_MODIFIER);
    X(III_AST_MOBIUS_CANDIDATE_DECL);
    X(III_AST_MOBIUS_CANDIDATE_MODIFIER);
    X(III_AST_SCHEMA_DECL);
    X(III_AST_SCHEMA_FIELD);
    X(III_AST_NARRATIVE_DECL);
    X(III_AST_NARRATIVE_FIELD);
    X(III_AST_CONST_DECL);
    X(III_AST_EXTERN_DECL);
    X(III_AST_EXTERN_ITEM);
    X(III_AST_DOC_ATTACHED);
    /* §6 */
    X(III_AST_TYPE);
    X(III_AST_BASE_TYPE);
    X(III_AST_PRIMITIVE_TYPE);
    X(III_AST_FUNCTION_TYPE);
    X(III_AST_TUPLE_TYPE);
    X(III_AST_ARRAY_TYPE);
    X(III_AST_GENERIC_ARGS);
    X(III_AST_HOLE);
    X(III_AST_RING_SET);
    X(III_AST_TIER_NAME);
    X(III_AST_REPLICATION_POLICY);
    X(III_AST_RANGE);
    X(III_AST_EPOCH_VALUE);
    X(III_AST_HEXAD_DESIGNATOR);
    X(III_AST_COHERENCE_EXPR);
    X(III_AST_COMPROMISE_TIER);
    /* §7 */
    X(III_AST_LET_STMT);
    X(III_AST_ASSIGN_STMT);
    X(III_AST_PLACE_EXPR);
    X(III_AST_IF_STMT);
    X(III_AST_MATCH_STMT);
    X(III_AST_MATCH_ARM);
    X(III_AST_FOR_STMT);
    X(III_AST_WHILE_STMT);
    X(III_AST_WAVEFRONT_STMT);
    X(III_AST_WAVEFRONT_MODIFIER);
    X(III_AST_WAVEFRONT_TERMINATOR);
    X(III_AST_SANCTUM_STMT);
    X(III_AST_METAL_STMT);
    X(III_AST_RETURN_STMT);
    X(III_AST_PROMOTE_STMT);
    X(III_AST_EXPLAIN_STMT);
    X(III_AST_PROPOSE_STMT);
    X(III_AST_PROPOSE_FIELD);
    X(III_AST_NEGOTIATE_STMT);
    X(III_AST_NEGOTIATE_ARG);
    X(III_AST_REFLECT_STMT);
    X(III_AST_COMMIT_STMT);
    X(III_AST_COMMIT_ARG);
    X(III_AST_REVERSE_STMT);
    X(III_AST_ASK_STMT);
    X(III_AST_EFFECT_STMT);
    X(III_AST_BLOCK_STMT);
    X(III_AST_BLOCK_EXPR);
    /* §8 */
    X(III_AST_EXPR_LVL_0);
    X(III_AST_EXPR_LVL_1);
    X(III_AST_EXPR_LVL_2);
    X(III_AST_EXPR_LVL_3);
    X(III_AST_EXPR_LVL_4);
    X(III_AST_EXPR_LVL_5);
    X(III_AST_EXPR_LVL_6);
    X(III_AST_EXPR_LVL_7);
    X(III_AST_EXPR_LVL_8);
    X(III_AST_EXPR_LVL_10);
    X(III_AST_EXPR_LVL_11);
    X(III_AST_EXPR_LVL_12);
    X(III_AST_EXPR_LVL_13);
    X(III_AST_PRIMARY);
    X(III_AST_LITERAL);
    X(III_AST_TUPLE_LITERAL);
    X(III_AST_RECORD_LITERAL);
    X(III_AST_RECORD_FIELD);
    X(III_AST_ARRAY_LITERAL);
    X(III_AST_CYCLE_INVOKE);
    X(III_AST_SANCTUM_INVOKE);
    X(III_AST_IRPD_CALL);
    X(III_AST_CALL);
    X(III_AST_INDEX);
    X(III_AST_FIELD_ACCESS);
    X(III_AST_PATH);
    X(III_AST_NAMED_ARG);
    X(III_AST_PHASE_CROSS);
    X(III_AST_EPOCH_BRIDGE);
    X(III_AST_CAP_ACQUIRE_RELEASE);
    X(III_AST_COHERENCE_QUERY);
    X(III_AST_GLYPH_MATERIALIZE);
    X(III_AST_WITNESS_EMIT);
    X(III_AST_REPLAY);
    X(III_AST_FULL_INVERSE_REPLAY);
    X(III_AST_INVERSE);
    X(III_AST_PREFIX_OP);
    X(III_AST_INFIX_OP);
    /* §9 */
    X(III_AST_LITERAL_PATTERN);
    X(III_AST_IDENT_PATTERN);
    X(III_AST_WILDCARD_PATTERN);
    X(III_AST_TUPLE_PATTERN);
    X(III_AST_RECORD_PATTERN);
    X(III_AST_RECORD_PATTERN_FIELD);
    X(III_AST_HEXAD_PATTERN);
    X(III_AST_TRIT_PATTERN);
    X(III_AST_RANGE_PATTERN);
    X(III_AST_PATH_PATTERN);
    X(III_AST_OR_PATTERN);
    X(III_AST_GUARD_PATTERN);
    /* Reserved */
    X(III_AST_RESERVED_001); X(III_AST_RESERVED_002); X(III_AST_RESERVED_003);
    X(III_AST_RESERVED_004); X(III_AST_RESERVED_005); X(III_AST_RESERVED_006);
    X(III_AST_RESERVED_007); X(III_AST_RESERVED_008); X(III_AST_RESERVED_009);
    X(III_AST_RESERVED_010); X(III_AST_RESERVED_011); X(III_AST_RESERVED_012);
    X(III_AST_RESERVED_013); X(III_AST_RESERVED_014); X(III_AST_RESERVED_015);
    X(III_AST_RESERVED_016); X(III_AST_RESERVED_017); X(III_AST_RESERVED_018);
    X(III_AST_RESERVED_019); X(III_AST_RESERVED_020); X(III_AST_RESERVED_021);
    X(III_AST_RESERVED_022); X(III_AST_RESERVED_023); X(III_AST_RESERVED_024);
    X(III_AST_RESERVED_025); X(III_AST_RESERVED_026); X(III_AST_RESERVED_027);
    X(III_AST_RESERVED_028); X(III_AST_RESERVED_029); X(III_AST_RESERVED_030);
    X(III_AST_RESERVED_031); X(III_AST_RESERVED_032);
    /* Diagnostic */
    X(III_AST_ERROR);
    X(III_AST_RECOVERY);

    #undef X
}

const char *iii_ast_kind_name(iii_ast_kind_t k) {
    init_table();
    if ((unsigned)k >= III_AST_KIND_COUNT) return "UNKNOWN";
    const char *s = NAME_BY_KIND[k];
    return s ? s : "UNKNOWN";
}
