// svir_asm.mjs -- a tiny SVIR assembler (dev tool): readable instruction lists -> SVIR v1 module bytes,
// formatted as a III u8 array.  Used to author svir_fact.iii reliably (the committed .iii holds the literal
// bytes; this is reproducible documentation, not a build dependency).
//   run: node svir_asm.mjs           (prints the byte array + the readable program)
import * as fs from 'node:fs';
const C=v=>[0x01,...(()=>{let b=[],x=BigInt.asUintN(64,BigInt(v));for(let i=0;i<8;i++){b.push(Number(x&0xffn));x>>=8n}return b})()];
const G=s=>[0x10,s], S=s=>[0x11,s], CALL=(f,a)=>[0x70,f,a], BR=d=>[0x50,d], BRIF=d=>[0x51,d];
const ADD=[0x20],SUB=[0x21],MUL=[0x22],SDIV=[0x23],SREM=[0x24],EQ=[0x30],LT=[0x32],GE=[0x33];
const BLOCK=[0x40],LOOP=[0x41],IF=[0x42],ELSE=[0x43],END=[0x44],RET=[0x60],PRINTC=[0x71],DROP=[0x72];
const flat=a=>a.flat(Infinity);
const GOLD=2432902008176640000n;  // 20!

// func 0 = main, 1 = fact_rec, 2 = fact_iter, 3 = print_dec
const funcs=[
 {name:'main',params:0,code:flat([            // locals: 0=r 1=s
   C(20),CALL(1,1),S(0),                        // r = fact_rec(20)
   C(20),CALL(2,1),S(1),                        // s = fact_iter(20)
   G(0),G(1),EQ,IF,ELSE,C(1),RET,END,           // if r!=s return 1
   G(0),C(GOLD),EQ,IF,ELSE,C(2),RET,END,        // if r!=golden return 2
   G(0),CALL(3,1),DROP,                          // print_dec(r)
   C(10),PRINTC,                                 // newline
   C(99),RET,
 ])},
 {name:'fact_rec',params:1,code:flat([          // n = local 0
   G(0),C(2),LT,IF,C(1),RET,END,                 // if n<2 return 1
   G(0),G(0),C(1),SUB,CALL(1,1),MUL,RET,         // return n * fact_rec(n-1)
 ])},
 {name:'fact_iter',params:1,code:flat([         // n=0 acc=1 i=2
   C(1),S(1), C(2),S(2),
   BLOCK,LOOP,
     G(2),G(0),C(1),ADD,GE,BRIF(1),              // if i >= n+1 break
     G(1),G(2),MUL,S(1),                          // acc *= i
     G(2),C(1),ADD,S(2),                          // i += 1
     BR(0),
   END,END,
   G(1),RET,
 ])},
 {name:'print_dec',params:1,code:flat([         // n = local 0
   G(0),C(10),GE,IF,                             // if n>=10:
     G(0),C(10),SDIV,CALL(3,1),DROP,             //   print_dec(n/10)
   END,
   C(48),G(0),C(10),SREM,ADD,PRINTC,             // print_char('0' + n%10)
   C(0),RET,
 ])},
];

function assemble(fl){ let m=[fl.length]; for(const f of fl){ const b=f.code; m.push(f.params,1,b.length&0xff,(b.length>>8)&0xff,...b); } return m; }
function iiiarr(m){ return `var SVIR : [u8; ${m.length}] = [\n    `+m.map(x=>x+'u8').join(',')+`\n]`; }

const M=assemble(funcs);
console.log(iiiarr(M));
console.log('\n// total bytes =',M.length,' golden 20! =',GOLD.toString());
for(const f of funcs) console.log('//  func',funcs.indexOf(f),f.name,'params',f.params,'body',f.code.length);

// ---- arbitrary-precision factorial (base-10 digit array in SVIR linear memory) ----
const L8=[0x80], ST8=[0x81];
function writeIII(path,mod,modname,note){
  const body=`/* ${path} -- generated by svir_asm.mjs.  ${note} */\nmodule ${modname}\n\n`+
    `var SVIR : [u8; ${mod.length}] = [\n    `+mod.map(x=>x+'u8').join(',')+`\n]\n\n`+
    `fn svir_ptr() -> u64 @export { return &SVIR as u64 }\nfn svir_len() -> u64 @export { return ${mod.length}u64 }\n`;
  fs.writeFileSync(path,body);
}
const N_FACT=100n;
const bigfuncs=[
 {name:'main',params:0,code:flat([            // local 0 = len
   C(N_FACT),CALL(1,1),S(0),                   // len = fact_big(N)
   G(0),CALL(2,1),DROP,                        // print_big(len)
   C(10),PRINTC, C(99),RET,
 ])},
 {name:'fact_big',params:1,code:flat([         // n=0 len=1 k=2 carry=3 i=4 prod=5 ; digits LE in mem
   C(0),C(1),ST8,  C(1),S(1),  C(2),S(2),       // digits[0]=1 ; len=1 ; k=2
   BLOCK,LOOP,                                   // for k=2..n
     G(2),G(0),C(1),ADD,GE,BRIF(1),             //   if k >= n+1: break
     C(0),S(3), C(0),S(4),                       //   carry=0 ; i=0
     BLOCK,LOOP,                                 //   for i=0..len-1
       G(4),G(1),GE,BRIF(1),                     //     if i >= len: break
       G(4),L8,G(2),MUL,G(3),ADD,S(5),           //     prod = digits[i]*k + carry
       G(4),G(5),C(10),SREM,ST8,                 //     digits[i] = prod % 10
       G(5),C(10),SDIV,S(3),                     //     carry = prod / 10
       G(4),C(1),ADD,S(4), BR(0),                //     i++
     END,END,
     BLOCK,LOOP,                                 //   while carry > 0
       G(3),C(0),EQ,BRIF(1),                     //     if carry == 0: break
       G(1),G(3),C(10),SREM,ST8,                 //     digits[len] = carry % 10
       G(3),C(10),SDIV,S(3),                     //     carry /= 10
       G(1),C(1),ADD,S(1), BR(0),                //     len++
     END,END,
     G(2),C(1),ADD,S(2), BR(0),                  //   k++
   END,END,
   G(1),RET,                                     // return len
 ])},
 {name:'print_big',params:1,code:flat([         // len=0 i=1 ; print digits[len-1..0]
   G(0),C(1),SUB,S(1),
   BLOCK,LOOP,
     G(1),C(0),LT,BRIF(1),                       // if i<0 break
     C(48),G(1),L8,ADD,PRINTC,                   // print '0' + digits[i]
     G(1),C(1),SUB,S(1), BR(0),
   END,END,
   C(0),RET,
 ])},
];
const memfuncs=[{name:'main',params:0,code:flat([C(3),C(42),ST8, C(3),L8, RET])}]; // store 42@3, load -> 42

if(process.argv[2]==='gen'){
  writeIII('svir_bignum.iii',assemble(bigfuncs),'svir_bignum',`arbitrary-precision ${N_FACT}! (base-10 digits in SVIR linear memory) -- prints the exact full result`);
  writeIII('svir_memtest.iii',assemble(memfuncs),'svir_memtest','SVIR linear-memory smoke test: store 42 at addr 3, load it, return -> 42');
  let gold=1n; for(let i=1n;i<=N_FACT;i++) gold*=i;
  console.error('wrote svir_bignum.iii ('+assemble(bigfuncs).length+' bytes), svir_memtest.iii. golden '+N_FACT+'! has '+gold.toString().length+' digits.');
}

// ---- debug isolation programs (main returns fact_X(5); expect exit 120) ----
if(process.argv[2]==='dbg'){
  const fr=funcs[1], fi=funcs[2];
  const mr=[{name:'main',params:0,code:flat([C(5),CALL(1,1),RET])}, fr];
  const mi=[{name:'main',params:0,code:flat([C(5),CALL(1,1),RET])}, fi];
  console.error('\n--- DBGR (fact_rec(5)) ---\n'+iiiarr(assemble(mr)));
  console.error('\n--- DBGI (fact_iter(5)) ---\n'+iiiarr(assemble(mi)));
}
