#!/usr/bin/env bash
# run_sqrtsum_kats.sh -- gate for the GENERAL sum-of-square-roots sign predicate (sqrt_sum_sign.iii):
# bigint_isqrt (handle-frugal) + ui_sqrt_sum_sign (separation-bound, arbitrary n, exact-zero detection).
# Links libiii_native.a (bigint/arena) and, for the agreement KAT, ui_exact_big.
set -u
III="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
I2="$III/COMPILED/iiis-2.exe"
A="$III/STDLIB/iii/aether"
LIB="$III/STDLIB/build/iii/libiii_native.a"
OUT="$(mktemp -d)"
pass=0; fail=0

"$I2" "$A/sqrt_sum_sign.iii" --compile-only --out "$OUT/sqrt_sum_sign.o" 2>"$OUT/s.log" || { echo "FAIL sqrt_sum_sign compile"; cat "$OUT/s.log"; exit 1; }
"$I2" "$A/kfield.iii"       --compile-only --out "$OUT/kfield.o"       2>"$OUT/kfw.log" || { echo "FAIL kfield compile"; cat "$OUT/kfw.log"; exit 1; }
"$I2" "$A/exact_surd_value.iii" --compile-only --out "$OUT/exact_surd_value.o" 2>"$OUT/esv.log" || { echo "FAIL exact_surd_value compile"; cat "$OUT/esv.log"; exit 1; }
"$I2" "$A/billiard.iii" --compile-only --out "$OUT/billiard.o" 2>"$OUT/bil.log" || { echo "FAIL billiard compile"; cat "$OUT/bil.log"; exit 1; }
"$I2" "$A/csg_tree.iii" --compile-only --out "$OUT/csg_tree.o" 2>"$OUT/ctr.log" || { echo "FAIL csg_tree compile"; cat "$OUT/ctr.log"; exit 1; }
"$I2" "$A/gas.iii" --compile-only --out "$OUT/gas.o" 2>"$OUT/gas.log" || { echo "FAIL gas compile"; cat "$OUT/gas.log"; exit 1; }
"$I2" "$A/gas_big.iii" --compile-only --out "$OUT/gas_big.o" 2>"$OUT/gb2.log" || { echo "FAIL gas_big compile"; cat "$OUT/gb2.log"; exit 1; }
"$I2" "$A/lattice_march.iii" --compile-only --out "$OUT/lattice_march.o" 2>"$OUT/lmr.log" || { echo "FAIL lattice_march compile"; cat "$OUT/lmr.log"; exit 1; }
"$I2" "$A/constraint.iii" --compile-only --out "$OUT/constraint.o" 2>"$OUT/cnr.log" || { echo "FAIL constraint compile"; cat "$OUT/cnr.log"; exit 1; }
"$I2" "$A/cspace.iii" --compile-only --out "$OUT/cspace.o" 2>"$OUT/csr.log" || { echo "FAIL cspace compile"; cat "$OUT/csr.log"; exit 1; }
"$I2" "$A/arc_sweep.iii" --compile-only --out "$OUT/arc_sweep.o" 2>"$OUT/asw.log" || { echo "FAIL arc_sweep compile"; cat "$OUT/asw.log"; exit 1; }
"$I2" "$A/resultant.iii" --compile-only --out "$OUT/resultant.o" 2>"$OUT/rsl.log" || { echo "FAIL resultant compile"; cat "$OUT/rsl.log"; exit 1; }
"$I2" "$A/refract.iii" --compile-only --out "$OUT/refract.o" 2>"$OUT/rfr.log" || { echo "FAIL refract compile"; cat "$OUT/rfr.log"; exit 1; }
"$I2" "$A/sturm_big.iii" --compile-only --out "$OUT/sturm_big.o" 2>"$OUT/sb2.log" || { echo "FAIL sturm_big compile"; cat "$OUT/sb2.log"; exit 1; }
"$I2" "$A/green_moments.iii" --compile-only --out "$OUT/green_moments.o" 2>"$OUT/gm.log" || { echo "FAIL green_moments compile"; cat "$OUT/gm.log"; exit 1; }
"$I2" "$A/photon3.iii" --compile-only --out "$OUT/photon3.o" 2>"$OUT/p3.log" || { echo "FAIL photon3 compile"; cat "$OUT/p3.log"; exit 1; }
"$I2" "$A/aether_lens_frame.iii" --compile-only --out "$OUT/aether_lens_frame.o" 2>"$OUT/alf.log" || { echo "FAIL aether_lens_frame compile"; cat "$OUT/alf.log"; exit 1; }
"$I2" "$A/ui_exact_big.iii"  --compile-only --out "$OUT/ui_exact_big.o"  2>"$OUT/u.log" || { echo "FAIL ui_exact_big compile"; cat "$OUT/u.log"; exit 1; }
"$I2" "$A/verb_geom.iii"     --compile-only --out "$OUT/verb_geom.o"     2>"$OUT/v.log" || { echo "FAIL verb_geom compile"; cat "$OUT/v.log"; exit 1; }
"$I2" "$A/traj_kinematics.iii" --compile-only --out "$OUT/traj_kinematics.o" 2>"$OUT/t.log" || { echo "FAIL traj_kinematics compile"; cat "$OUT/t.log"; exit 1; }
"$I2" "$A/exact_denest.iii"  --compile-only --out "$OUT/exact_denest.o"  2>"$OUT/d.log" || { echo "FAIL exact_denest compile"; cat "$OUT/d.log"; exit 1; }
"$I2" "$A/csg_kernel.iii"    --compile-only --out "$OUT/csg_kernel.o"    2>"$OUT/csg.log" || { echo "FAIL csg_kernel compile"; cat "$OUT/csg.log"; exit 1; }
"$I2" "$A/photon_route.iii"  --compile-only --out "$OUT/photon_route.o"  2>"$OUT/pr.log" || { echo "FAIL photon_route compile"; cat "$OUT/pr.log"; exit 1; }
"$I2" "$A/cyclotomic_se3.iii" --compile-only --out "$OUT/cyclotomic_se3.o" 2>"$OUT/cse3.log" || { echo "FAIL cyclotomic_se3 compile"; cat "$OUT/cse3.log"; exit 1; }
"$I2" "$A/q23_sign.iii"      --compile-only --out "$OUT/q23_sign.o"      2>"$OUT/q23s.log" || { echo "FAIL q23_sign compile"; cat "$OUT/q23s.log"; exit 1; }
"$I2" "$A/collide.iii"       --compile-only --out "$OUT/collide.o"       2>"$OUT/col.log" || { echo "FAIL collide compile"; cat "$OUT/col.log"; exit 1; }
"$I2" "$A/choreo.iii"        --compile-only --out "$OUT/choreo.o"        2>"$OUT/cho.log" || { echo "FAIL choreo compile"; cat "$OUT/cho.log"; exit 1; }
"$I2" "$A/delaunay.iii"      --compile-only --out "$OUT/delaunay.o"      2>"$OUT/dln.log" || { echo "FAIL delaunay compile"; cat "$OUT/dln.log"; exit 1; }
"$I2" "$A/sturm.iii"         --compile-only --out "$OUT/sturm.o"         2>"$OUT/stm.log" || { echo "FAIL sturm compile"; cat "$OUT/stm.log"; exit 1; }
"$I2" "$A/aether_lens.iii"   --compile-only --out "$OUT/aether_lens.o"   2>"$OUT/al.log" || { echo "FAIL aether_lens compile"; cat "$OUT/al.log"; exit 1; }
"$I2" "$A/algnum.iii"        --compile-only --out "$OUT/algnum.o"        2>"$OUT/an.log" || { echo "FAIL algnum compile"; cat "$OUT/an.log"; exit 1; }
"$I2" "$A/brep3.iii"         --compile-only --out "$OUT/brep3.o"         2>"$OUT/b3.log" || { echo "FAIL brep3 compile"; cat "$OUT/b3.log"; exit 1; }
"$I2" "$A/inertia3.iii"      --compile-only --out "$OUT/inertia3.o"      2>"$OUT/i3.log" || { echo "FAIL inertia3 compile"; cat "$OUT/i3.log"; exit 1; }
"$I2" "$A/crystal3.iii"      --compile-only --out "$OUT/crystal3.o"      2>"$OUT/cr3.log" || { echo "FAIL crystal3 compile"; cat "$OUT/cr3.log"; exit 1; }

run() {
    local name="$1" want="$2"; shift 2
    "$I2" "$III/STDLIB/corpus/$name.iii" --compile-only --out "$OUT/$name.o" 2>"$OUT/$name.c.log" || { echo "FAIL  $name : compile"; fail=$((fail+1)); return; }
    rm -f "$OUT/$name.exe"
    gcc "$OUT/$name.o" "$@" -lws2_32 -lkernel32 -o "$OUT/$name.exe" 2>"$OUT/$name.l.log" || { echo "FAIL  $name : link"; grep -i undefined "$OUT/$name.l.log" | head; fail=$((fail+1)); return; }
    local st="$OUT/${name}.run.exe"; cp "$OUT/$name.exe" "$st"
    timeout 300 "$st"; local rc=$?
    rm -f "$st"
    if [[ "$rc" == "$want" ]]; then echo "PASS  $name : exit $rc"; pass=$((pass+1)); else echo "FAIL  $name : exit $rc (want $want)"; fail=$((fail+1)); fi
}

run 2120_bigint_isqrt   99   "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"
run 2121_sqrt_sum_sign  99   "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$OUT/ui_exact_big.o" "$LIB"
run 2122_lazy_real      99   "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$OUT/ui_exact_big.o" "$LIB"   # lazy tier-1 interval + tier-3 escalation, counted
run 2123_lazy3          99   "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$OUT/ui_exact_big.o" "$LIB"   # ATTACK 1+3: canonicalization Tier 2 + adaptive-F windowing
run 2124_transcendental 99   "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$OUT/ui_exact_big.o" "$LIB"   # ATTACK 2: transcendental tristate (UNKNOWN, no panic)
run 2125_verb_geom      99   "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$OUT/ui_exact_big.o" "$LIB"   # GRAPH RESTORED: e-class equivalence substrate + sign cache
run 2137_adaptive_sign  99   "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"   # TIER 2.5: linear-independence + adaptive precision -- bypasses the exponential separation bound per-instance
run 2138_symmetry_quotient 99 "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # SYMMETRY QUOTIENT: real Euclidean perimeter comparisons -- pay the exact-sign wall once per distinct shape (similarity/relabel/swap orbit)
run 2139_padic_barrier   99   "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # P-ADIC WALL FACE: factoring-free modular sieve is UNSOUND (mod p destroys perfect-square factors); sound arm needs factoring => redundant
run 2140_adaptive_big    99   "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # TIER 2.5 BIGINT-COEFF: adaptive sign for caller-owned bigint magnitudes (the ui_sqrt_sum_sign_big / ui_arc_cover_full render-scale path)
run 2141_cyclotomic_rotation 99 "$OUT/cyclotomic_se3.o" "$LIB"  # EXACT cyclotomic rotation: rational-multiple-of-π angles in ℚ(√2,√3); 24×15° returns bit-exact to identity; DEDUPED onto cyclotomic_se3::q23_mul (pure organ, no Σ√ dep)
run 2142_se3_screw       99   "$OUT/cyclotomic_se3.o" "$LIB"  # EXACT SE(3) screw: 3D rotation closure + SO(3) non-commutativity + exact screw translation in ℚ(√2,√3); DEDUPED onto cyclotomic_se3::q23_mul
run 2143_traj_arclen     99   "$OUT/traj_kinematics.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # LOAD-BEARING: traj_len_sign consumes the bigint adaptive tier -- exact gantry-trajectory length comparison (3+ independent surds at bigint scale)
run 2144_lattice_pathfind 99  "$OUT/traj_kinematics.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # HIGH-END PATHFINDING: exact lattice Dijkstra (lattice_shortest_path) -- frontier ordered by EXACT Sqrt-sum length; matches brute-min, resolves a float-blind Pell near-tie
run 2145_denest          99   "$OUT/exact_denest.o"  # TOWER DENESTING: exact rank-1 sqrt of a+b*sqrt(d) in Q(sqrt d) -- decides square-vs-extension, verified root; rejects the norm-square-but-not-alpha case
run 2146_compactor       99   "$OUT/traj_kinematics.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # FRONTIER COMPACTOR: drop settled Dijkstra distances (dead to the search) -> peak handles = frontier width; correct + behavior-preserving on a 100-node graph
run 2147_lattice_oracle  99   "$OUT/traj_kinematics.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # Oh QUOTIENT ORACLE: O(1) exact shortest king-move-lattice distance via octahedral symmetry; oracle==greedy, greedy beats both competitors
run 2150_csg_kernel      99   "$OUT/csg_kernel.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$OUT/exact_denest.o" "$LIB"  # UNSHATTERABLE CSG: exact quadric membership/incidence (Sum-sqrt) + tangency (integer) + triple-point corner (denest); float-breaks near-tie witness
run 2151_photon_route    99   "$OUT/photon_route.o" "$OUT/traj_kinematics.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # PHOTONIC LATTICE ROUTING: O(1) O_h bulk geodesic (millions of nodes, zero memory) + exact zero-loss near-tie compare + frontier-compacted defect detour
run 2152_mechanism       99   "$OUT/cyclotomic_se3.o" "$OUT/q23_sign.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # ZERO-DRIFT KINEMATICS: exact ℚ(√2,√3) rotation, bit-exact home after 2400 steps (100 rev) + q23_sign exact reach ordering (Σ√ unification) + SE(3) screw
run 2153_collision       99   "$OUT/collide.o" "$OUT/cyclotomic_se3.o" "$OUT/q23_sign.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # NO-TUNNELING COLLISION: exact swept-segment vs sphere (endpoints clear yet HIT) + certified tangency + rotated-tool Σ√ membership (cyclotomic_se3 ⊗ geometry)
run 2485_choreography    99   "$OUT/choreo.o" "$OUT/resultant.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # E-IV MULTI-AGENT EXACT CHOREOGRAPHY: rs_elim tangency-design (Res_t sep2 = 64u^2-256, grazing u=+-2) + exact Q(sqrt2) TOI/graze/miss via surd-sign + THE COMMUTING-EVENT PLANNER (disjoint agent-pairs commute BIT-IDENTICALLY, interacting ties genuinely diverge + refused -- non-vacuous teeth) + surd disc 176+96sqrt2
run 2154_delaunay        99   "$OUT/delaunay.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # ROBUST PREDICATES: exact orient2d/incircle2d (consistent signs, no invalid topology) + Fibonacci-Cassini float-blind witness (exact -1 where a double returns 0) + Delaunay flip + Σ√ orient
run 2156_sturm           99   "$OUT/sturm.o" "$LIB"  # EXACT ROOT ISOLATION: Sturm's theorem, exact real-root count/isolation; positive-at-both-endpoints-yet-2-roots-inside witness (endpoint-sampling finds 0, Sturm counts 2); squarefree-part gcd
run 2155_aether_lens     99   "$OUT/aether_lens.o" "$OUT/aether_lens_frame.o" "$OUT/cyclotomic_se3.o" "$OUT/q23_sign.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # EXACT RAY-CAST: floating-point-free ray∩quadric CSG -- integer sign(Delta) hit/miss/tangent + n=3 surd depth order (z-FIGHT KILLER: fixed f=10 straddles [-2,+2], exact resolves +1) + n=2 surd DERIVED 8-bit Lambert; renders a shaded sphere as first light
run 2157_algnum          99   "$OUT/algnum.o" "$OUT/sturm.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # EXACT ALGEBRAIC NUMBERS: sign/total-order/decidable-EQUALITY (the zero problem) -- sqrt(2) three ways decided EQUAL via gcd-shared-root (a refine-to-epsilon impostor loops/guesses); sqrt(2)<cbrt(3)/<99/70 by refinement; face1⊗face6 -- Sturm sign == Sigma-sqrt separation-bound sign over a rational fan; composes sturm.iii + sqrt_sum_sign.iii
run 2159_kf_weld        99   "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$OUT/exact_surd_value.o" "$LIB"  # THE WELD GATE: kfield Galois-tower sign as Tier 3 -- differential vs the separation-bound oracle (19/39 overflow family -> 39/39 guarded abstains; Pell near-ties DECIDED in pure i64 by the tower; rank-collapse {6,10,15} F2-embed; rank-4 abstain->adaptive fallback).  THEOREM: bounded-rank Galois-tower sign == separation-bound sign
run 2148_theorem_fuzzer  99   "$OUT/kfield.o" "$LIB"  # QUOTIENT-KIT landed: generative coincidence-fuzzer over kfield (CONSTRUCT/IDENTIFY verbs; identity pairs collide, control does not)
run 2149_universal_block 99   "$OUT/kfield.o" "$LIB"  # QUOTIENT-KIT landed: the universal block -- kfield four verbs = ONE kernel; addr-coincidence <=> sign-zero (IDENTIFY <=> DECIDE)
run 2167_billiard_reversal 99 "$OUT/billiard.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # EXACT TIME-REVERSIBLE BILLIARDS (charter Phase 1): 12 events forward + reverse = BIT-EXACT return + wall palindrome (irrational 45-deg offset orbit); Q32.32 twin picks the WRONG wall on the certified near-tie; corner tie CERTIFIED and refused
run 2168_csg_tree       99 "$OUT/csg_tree.o" "$OUT/csg_kernel.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$OUT/exact_denest.o" "$LIB"  # ALGEBRAIC CSG DAG (charter Phase 5): 1000 successive drills, the 1000th op as precise as the 1st (depth composes booleans not arithmetic); ON-certificate carried through 1000 ops; leaf exactness at 2^62 where a 53-bit-mantissa twin collapses R^2 and R^2+1
run 2433_gas_reversal   99 "$OUT/gas.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # THE EXACT MICROCANONICAL GAS (Program II Phase I): N-body hard-cube gas -- pair collisions = integer component SWAPS (energy+momentum = INTEGER IDENTITIES at every event); ensemble involution R.F^7.R.F^7 == id BIT-EXACT; two-pair simultaneity CERTIFIED and refused
run 2170_swept_leaf     99 "$OUT/csg_tree.o" "$OUT/csg_kernel.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$OUT/exact_denest.o" "$LIB"  # THE SWEPT-SPHERE LEAF (Program II Phase II / Vector I base): CSG leaves as continuous spacetime volumes -- exact clamped-parabola membership at ANY t; ON-certificates through booleans; 100-pass zigzag depth-independent; the snapshot CAM twin leaves PHANTOM MATERIAL at t*=5/8 where the exact leaf proves the cut
run 2171_lattice_march  99 "$OUT/lattice_march.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # INFINITE PERIODIC TIR OPTICS (Phase 4 / Vector III): 2,999,997 exact crossings to the sphere at x-cell 999999 (EXACT integers, zero drift, zero storage); 50-bounce mirror labyrinth retraced BIT-EXACTLY; disc==0 certified tangent; corner-tie double-step vs the biased-DDA twin entering a mirror cell the true ray never touches
run 2172_constraint     99 "$OUT/constraint.o" "$OUT/sturm.o" "$OUT/delaunay.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # EXACT 1-DOF CONSTRAINT RESOLUTION (Phase 3 + II-V / Vector II): Sturm count/isolate + gcd(p,pPRIME) SINGULARITY certificate (the irrational tangent config sqrt2 EXACTLY bracketed); sign-sampling is STRUCTURALLY blind to tangential roots (1 vs 2, even with exact evaluation); the incircle flip-instant isolated and cross-certified by delaunay incircle2d == 0
run 2173_cspace         99 "$OUT/cspace.o" "$OUT/arc_sweep.o" "$OUT/sturm.o" "$OUT/cyclotomic_se3.o" "$OUT/q23_sign.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # THE EXACT C-SPACE COMPILER (II-III / Vector I): 24x6x3 cyclotomic states decided by q23_sign (irrational blocked certificate); TRANSLATION edges SWEPT-certified -- a both-endpoints-free edge is KILLED where the tip sweep tunnels (the endpoint-only twin walks through, 4 vs 6); BFS discovered the k=2 ZERO-CLEARANCE tangent corridor (10 < the author-planned 12); rotation arc-sweep = charted OPEN
run 2175_arc_sweep      99 "$OUT/arc_sweep.o" "$OUT/cspace.o" "$OUT/sturm.o" "$OUT/cyclotomic_se3.o" "$OUT/q23_sign.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # ROTATIONAL ARC-SWEEP CERTIFICATE (Program III Vector VI): Weierstrass quartic + R(180) integer chart + machine-derived /1000 covers; the arc GRAZE with free endpoints REFUSED (rotational tunneling no endpoint sampler sees); the certified planner circles the ring 22 moves where the twin sweeps through matter in 2; C-space rotation edges now CONTINUOUSLY certified
run 2176_gas_big       99 "$OUT/gas_big.o" "$OUT/gas.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # TRANS-ENVELOPE THERMODYNAMICS (Program III Vector V): the i64 gas honestly refuses at 2^61 magnitude; the bigint ensemble continues the SAME scenario (involution exact AS RATIONALS) and runs 200 events deep -- velocities never migrate (integer identities); handle-table discipline: sign calls in their own dropped arenas
run 2183_gas_compact   99 "$OUT/gas_big.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # ENSEMBLE COMPACTION (charter increment 5): gcd-reduce numerators+denominator via Knuth-division Euclid, migrate to a FRESH arena (bump bytes reclaimed) -- snap_diff==0 across the call (dynamically INVISIBLE, snapshot migrated verbatim); STRICT bit ratchet 35->3 at event 10; maximality (second compact = 0); mid-run compaction transparent to the involution; 120-event twin: identical history (120/120 kinds, 9/9 velocities) with 6 limbs -> 1 limb
run 2188_gas_deep      99 "$OUT/gas_big.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # THE DEEP ENSEMBLE (Turing charter V-II.1): 9999 forward + 9999 reversed steps under the den-bits-48 THRESHOLD COMPACTION LAW (1254 compactions, arena migrations on BOTH legs) -- involution snap_diff==0, energy integer identity 462, den <= 38 bits at close; THE COMMUTING-TIE RESOLUTION (disjoint (particle,axis) slots => responses commute, applied both; interacting ties still refuse) unlocked the depth: 28 simultaneous pairs resolved lawfully (20027 responses / 19999 steps, pinned)
run 2195_gas_100k      99 "$OUT/gas_big.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # THE 10^5-STEP ENSEMBLE (Turing-next N-3): 49999 forward + 49999 reversed steps under the den-bits-48 law -- involution snap_diff==0 through 6269 compactions and 277 lawfully-resolved commuting pairs (100275 responses PINNED); energy the same integer 462; den 38 bits at close; ~105 s
run 2198_shadow_family 99 "$OUT/gas_big.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # SHADOW PERTURBATION FAMILIES (Turing-next N-6): the divergence table -- four one-quantum kicks (P0.vx/P1.vx/P2.vz/P0.vz) give EXACT first-divergence indices (11, 10, 9, 11), the vz kick reaching the event skeleton fastest, cross-consistent with 2189; a member may meet its own certified tie downstream (member 4 at 372) -- the table stands on prefixes, k* strictly inside each; the P1.vy kick would recreate the DOCUMENTED 2176 graze-tie at step 0 (noted, sidestepped)
run 2189_shadow        99 "$OUT/gas_big.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # THE LYAPUNOV SHADOW (Turing charter V-II.2, adjudicated): one momentum quantum (vz 7->8) -- NINE identical responses then the EXACT first-divergence index k*=9; exact velocity separations 95/81/63 at 500/1500/3000 steps; THE MACHINE REFUTED the drafted strictly-growing pin: bounded gas conserves the velocity multiset up to sign, so separation FLUCTUATES -- chaos = permanent decorrelation (never re-sync) + different event densities (3006 vs 3011), never a fitted exponent
run 2190_photon3       99 "$OUT/photon3.o" "$OUT/q23_sign.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # 3D PHOTON CLASS ALGEBRA Q(sqrt2,sqrt6) (Turing charter V-III.1+III.2): closure table as integer identities (L<->D residue 0, critical 0, TIR +2/+6) + the sqrt5 NON-CLOSURE witness (cross-axis a^2=5: the wave-vector constraint); CERTIFIED CONFINEMENT -- 1000 reflective events (548 TIR + 452 critical), den NEVER grew (z-parity invariant), state exactly in-box; NON-RECURRENCE: all 1000 exact states pairwise distinct (sqrt2-incommensurate periods -- trapped forever, repeating never); the D-class escape twin transmits (residue 0)
run 2191_graze_legal   99 "$OUT/arc_sweep.o" "$OUT/sturm.o" "$LIB"  # THE GRAZE-LEGAL ARC VERB (Turing charter V-IV.1): as_cert2 upgrades ONLY the refusal path via root_mult on the refusing call's own AS_P -- the 2181 geometry at verb level: r2=225 graze as_cert 0 -> as_cert2 2 (LEGAL: one root, mult 2, N>=0 throughout); r2=226 crossing stays 0; r2=4 clear both 1 (conservative); as_cert untouched, 2181/2175 regated
run 2192_dynamic_toi   99 "$OUT/cspace.o" "$OUT/arc_sweep.o" "$OUT/sturm.o" "$OUT/cyclotomic_se3.o" "$OUT/q23_sign.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # V-IV.2: cs_set_graze routes rotation edges through as_cert2 -- the tangency lies in BOTH adjacent arc covers so normal mode cannot rotate AT ALL (cs_plan -1) while graze mode finds the 2-move plan through the certified corridor; TIME in the certificate: transient occlusion EXACTLY [7,13] (mult 1+1) where every static snapshot in [5,15] says blocked; graze-in-TIME mult 2 at the exact instant t=10 (transit legal)
run 2197_edge_graze    99 "$OUT/cspace.o" "$OUT/arc_sweep.o" "$OUT/sturm.o" "$OUT/cyclotomic_se3.o" "$OUT/q23_sign.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # GRAZE-NAMED TRANSLATION EDGES (Turing-next N-5): the swept-parabola interior minimum IS the trichotomy (the arc cover needed multiplicity; the translation formulation sees tangency free) -- exact zero at r2=25, +-1600 at 24/26 (verdicts 2/1/0 pinned); the planner crosses the graze edge legally (1 move); sv==0 gated for the first time
run 2193_elim          99 "$OUT/resultant.o" "$LIB"  # MULTIVARIATE ELIMINATION (Turing-next N-1): Res_u of bivariate grids through the factored 16-prime pipeline with degeneracy-SKIPPING nodes -- Res_u(u^2-t, u-2) = t-4 closed form; THE IMPASSABILITY CONSTANT: Res_t(p, dp/dt) over the 2192 departure family = -36 DEGREE ZERO in c (disc 36>0 for EVERY unit-speed departure: the universal quantifier cashed by elimination); Res_u(u^2-t^2, u-t) IDENTICALLY ZERO (the common-component criterion); refusals (no u-degree, zero lead row)
run 2194_crystal       99 "$OUT/photon3.o" "$OUT/q23_sign.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # THE 2-D PHOTONIC CRYSTAL (Turing-next N-2): alternating dense/light z-layers between TIR walls -- 8 events (certs 0/6/0/0/6/0/2/0: the class-dependent TIR margins LIVE), two razor-thin orderings (0.05, 0.02) decided by q23_sign; THE MACHINE-FOUND SUBRING THEOREM: same-class deposit/consume pairing means sqrt3 = sqrt2*sqrt6 NEVER forms -- the reachable ring is rank-3 {1,sqrt2,sqrt6}, sqrt3 slots pinned identically zero; final state exact to twelve slots
run 2177_resultant     99 "$OUT/resultant.o" "$OUT/sturm.o" "$LIB"  # RESULTANT ELIMINATION (Program III Vector VII): gamma = alpha + beta constructed via interpolated Bareiss Sylvester determinants -- the classical minimal polynomials of cbrt2+sqrt3 (deg 6) and sqrt2+sqrt3 (deg 4) derived COEFFICIENT-FOR-COEFFICIENT, then composed back through sturm (2 real roots; gamma bracketed in (2.9,3]) -- roots closed under +
run 2179_resultant_big  99 "$OUT/resultant.o" "$LIB"  # MODULAR-CRT DETERMINANT ENGINE (charted v2): 16-prime Gauss + Garner CRT + certified permanent bound -- v1 Bareiss REFUSES at cbrt(2^31)+sqrt3 (overflow) and at D=12 (guard); v2 derives both EXACTLY (constant 2^62-27; monic deg-12 with t^11=t^10=0, R(0)=73, both real roots bracketed by exact Horner); Bareiss==CRT twin weld on the shared envelope; coefficient-beyond-i64 certified refusal
run 2180_resultant_closure 99 "$OUT/resultant.o" "$OUT/sturm.o" "$LIB"  # CLOSURE VERBS (charter increment 2): roots closed under * (norm forms (t^2-6)^2, t^6-108; rs_prod_big t^12-648 where v1 guard-refuses) and INVERSE (x^4-10x^2+1 SELF-reversed; 1/cbrt2 -> 2x^3-1; f(0)=0 and g(0)=0 certified refusals) + content strip -- THE GOLDEN RATIO composed (1+sqrt5)*(1/2) via sum,prod,primitive -> t^2-t-1, sturm 1 root in [1,2] and 1 in [-1,0]; zero-lead Sylvester degeneracy HARDENED to refusal
run 2181_arc_tangency   99 "$OUT/sturm.o" "$OUT/arc_sweep.o" "$LIB"  # ROOT MULTIPLICITY (charter increment 3): touch-vs-cross discriminator via iterated gcd(p,p') PRS -- (u^2-2)^2(u^2-3) mult 2 at sqrt2 / 1 at sqrt3 with BOTH-ENDS-NEGATIVE blindness witness (-26,-3); the arc_sweep GRAZE (N=400u^2(u^2+1), as_cert refuses 0) certified EVEN=touch vs r2=226 crossing certified ODD -- same conservative verdict, different certificate; -1 rootless / -2 ambiguous refusals
run 2182_march_v2       99 "$OUT/lattice_march.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # RATIONAL-DIRECTION MARCH v2 (charter increment 4): ANY integer direction via the DHAT-refined-lattice isomorphism (every event time/position INTEGER) -- 12000 crossings d=(5,7) with the PARITY THEOREM certifying zero corners + exact Sturmian state (1050055,1470000); 12000 reversed crossings land BIT-EXACTLY on the first forward crossing; exact corner double-step d=(2,3) vs the x-first biased twin entering the sum-4 cell the ray never touches; general-d sphere: disc==0 CERTIFIED tangent / hit / miss on one geometry
run 2178_refract       99 "$OUT/refract.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # BOUNDED-RANK REFRACTION (Program III Vector VIII): the designed 45<->30-degree closed class pair (n^2 = 1|2) -- Snell-squared as a CERTIFIED integer identity per transition; the exact slab theorem (exit parallel, lateral shift (300+100sqrt3)/3); the EXACT critical angle (residue 0); TIR certified (+2); no tower, ever
run 2184_photon_stack   99 "$OUT/refract.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # MULTI-INTERFACE OPTICS (charter increment 6): the periodic stack -- 20 CERTIFIED interfaces (residues all 0), iterated slab theorem (exit PARALLEL, walk-off EXACTLY 280+100sqrt3, y=-480, den 1); the GUIDED MODE -- 1000 strict TIR bounces (+2 each), pitch EXACTLY -9995sqrt3; the 45-class held only MARGINALLY (certified-zero critical) in the same channel; boundary/out-of-band/class-parity refusals; band index COMBINATORIAL (no region signs to get wrong)
run 2185_sturm_big     99 "$OUT/sturm_big.o" "$OUT/sturm.o" "$OUT/resultant.o" "$LIB"  # BIGINT PRS (Turing charter V-I.1): the chain in RAW POOL ARRAYS (a full bigint chain would exceed the 64-slot handle table), transient handles only -- the deg-12 wall CROSSED (i64 chain garbage -4 pinned as twin; sturm2 counts EXACTLY 2, brackets match 2179 Horner); the CRT->PRS weld at deg 16 (2^(1/4)+3^(1/4): 4 roots, both isolations); multiplicity 2 at sqrt2+sqrt3 past the wall; deg-25 refusal
run 2186_resultant_abi 99 "$OUT/resultant.o" "$OUT/sturm_big.o" "$LIB"  # BIGINT OUTPUT ABI (Turing charter V-I.2): the 2179-D refusal now DELIVERS -- a^2-27 = 2^80-27 as raw limbs (18446744073709551589, 65535) fit-flagged, every fitting coefficient in out[], the mod-every-prime check run on FULL limb values; the raw rows bridge into sturm_big: 2 real roots isolated at 10319/10323 with no i64 anywhere in the object; shared-envelope twin equality
run 2187_green_moments 99 "$OUT/green_moments.o" "$LIB"  # EXACT MOMENTS (Turing charter V-I.3): integral x^2 over [0,sqrt2] = (0,2,3) EXACT rank-1 (irrational -- the anti-mesh certificate: NO rational tessellation can equal it); first moment = 1 EXACTLY RATIONAL from the irrational domain (radicals cancel); inertia kernel 4sqrt2/5; centroid as the integer identity 4Mx == 3sqrt2*A; the 4-panel trapezoid twin provably ABOVE by certified i64 sign; pi-domains structurally absent + refusals
run 2196_moments_big   99 "$OUT/green_moments.o" "$LIB"  # BIGINT MOMENTS (Turing-next N-4): the i64 Horner passes 1.35e19 mid-flight and honestly refuses at K=1.5e6*sqrt2 -- the bigint field Horner (signed pairs, own dropped arena) delivers the fully-reduced exact triple (0, 2.25e18, 1) = 2sqrt2K^3/3 (the machine out-reduced the author: gcd 6, not 2); twin weld triple-for-triple on the 2187 envelope; K=3e6 output-width refusal
run 2174_gas_demon      99 "$OUT/gas.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # THE SPEED-SELECTIVE MEMBRANE (Vector IV, the exact Maxwell demon): slow particles CONFINED (3 exact membrane bounces, contact-on-membrane legal), the fast particle passes and works the far wall; energy an integer identity at every event; the DIRECTION-BLIND gate is reversal-symmetric -- the involution holds WITH the demon active (a reversible demon pumps no entropy, gated)

run 2473_elim3          99   "$OUT/resultant.o" "$LIB"  # TRIVARIATE ELIMINATION (Vector I escalation): Res_z of trivariate grids as a CERTIFIED bivariate polynomial -- 16-prime tensor pipeline (fixed-layout Sylvester dets at (Dx+1)x(Dy+1) nodes, two-stage Lagrange, Garner CRT via the SHARED rs_crt_center kernel, node-by-node consistency); closed forms, the SPECIALIZATION WELD onto 2193's rs_elim at three slices, common-component identically-zero, the -2^63 coefficient REFUSED strict / DELIVERED as raw rows (rs_elim3_big), refusals
run 2474_brep_edge      99   "$OUT/brep3.o" "$OUT/resultant.o" "$OUT/sturm.o" "$OUT/sturm_big.o" "$LIB"  # THE EXACT 3D B-REP EDGE (CAD-lite): sphere x paraboloid -- b3_zred H = s z + (s-4) (the edge as an exact RATIONAL MAP over its shadow), WELD A rs_elim3(F,H) == direct-substitution C, WELD B C == h0 * shadow (Res multiplicativity), slice+Sturm 2 real edge points, second-axis fiber (z^2+z-4)^2 with the complex-branch caveat pinned; sphere x cone -- z-FREE reduction, shadow = 4(s-2)^2 (two-sheet multiplicity SQUARED, welded), GLOBAL fiber z^2-2 from BOTH surfaces, +-sqrt2 isolated with exact sign-change brackets; THE BIG WIRE: rs_elim3_big rows -> b3_slice_x_big -> sturm_big (no i64 anywhere), root_count2 == 2
run 2479_inertia3       99   "$OUT/inertia3.o" "$OUT/cyclotomic_se3.o" "$LIB"  # EXACT 3D INERTIA TENSOR in Q(sqrt2,sqrt3) (green_moments -> 3D tensor calculus): sqrt2-edge tetra V = sqrt2/3 EXACT, int x = 1/6 EXACTLY RATIONAL from the irrational domain; THE DIVERGENCE TWIN (outward face fluxes, 2-simplex weights) welds all four moment shapes; simplicial ADDITIVITY across a midpoint split; the binomial TRANSLATION LAW (Steiner's engine) + I_xx translation-invariance; THE TENSOR TRANSFORMATION LAW I(R body) == R I R^T at exact 15 degrees, 36 cells cross-multiplied equal; product-guard refusals
run 2480_inverse_design 99   "$OUT/resultant.o" "$OUT/sturm.o" "$OUT/cyclotomic_se3.o" "$OUT/q23_sign.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"
run 2481_exact3_fuzz    99   "$OUT/resultant.o" "$OUT/sturm.o" "$OUT/inertia3.o" "$OUT/cyclotomic_se3.o" "$LIB"  # THE UNSCRIPTED ADVERSARY: property/differential fuzzing on inputs no author saw -- planted-zero shadow completeness (theorem-forced, 3 disjoint-prime residues), textbook-COFACTOR Sylvester differential (checker-local algorithm, fresh primes), elimination-vs-Sturm QE trichotomy on random contact families (two organs gated years apart), inertia3 theorem sweep (twin/translation/covariance/additivity) on random q23 tetrahedra INCLUDING degenerates; zero authored constants; EXACT3_SEED/EXACT3_CASES env = the evergreen user channel (unset -> deterministic 250/family); TEETH: a 1-char engine mutation reddens it 236/450 while the untouched family stays green  # ONE-PARAMETER INVERSE DESIGN (QE reversed): B(c) = Res_t(p, dp/dt) = 4c^2-32c+32 -- safe-for-ALL-t <=> B > 0; Sturm isolates the boundary 4 -+ 2sqrt2, the endpoints verified EXACT ZEROS in Q(sqrt2) (control rejected); inside witnessed unsafe (2 contact instants), outside certified safe UNIVERSALLY (0 roots + positive value); the composed reach constraint c >= 2 decided by q23_sign: the feasible set EXACTLY (4+2sqrt2, inf), witness c = 7

run 2482_loschmidt_echo 99   "$OUT/gas_big.o" "$OUT/gas.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # THE EXACT LOSCHMIDT ECHO (E-II): perfect echo defect 0 (theorem); ONE-QUANTUM imperfect reversal -> EXACT integer defects (n=7: 3 slots, sum 17, energy shift 7 = 2v+1 identity); kick-unkick restores id (theorem); depth table 5/7/9 pinned -- the machine CONFIRMS 2189 live (n=9 defect SMALLER than n=5: separation fluctuates, no exponent fitted); THE KS ADJUDICATION: h_KS is an asymptotic limit NO finite exact run certifies -- delivered instead as EXACT word counts W(L) of the 2500-step event skeleton (22/265/2124/2471/2493) vs the integrable control (W==2 flat): chaos as integers, never an estimate
run 2483_crystal3       99   "$OUT/crystal3.o" "$OUT/photon3.o" "$OUT/q23_sign.o" "$OUT/verb_geom.o" "$OUT/sqrt_sum_sign.o" "$OUT/kfield.o" "$LIB"  # THE 3D PHOTONIC CRYSTAL CAVITY (E-III): 300 certified events (56 x-mirror / 76 y-mirror / 112 interface / 56 cap); den prime-support EXACTLY {2,3}; THE MACHINE-FOUND AXIS-STRATIFIED RANK BOUND: transverse axes NEVER form sqrt3 (rank-3 {1,sqrt2,sqrt6}) while the optical axis reaches rank-4 -- 2194's subring theorem in 3D; exact 6-face membership at every event + non-recurrence (300 distinct states); aperture control escapes at event 2; EXACT PHASE: the x<->y mirror symmetry's clock difference is EXACT ZERO by q23_sign (constructive interference as an identity) and the inequivalent-lattice near-tie DT = -24sqrt2 - 22sqrt6 (rational slot ZERO: the surd-blind comparator says EQUAL, q23_sign decides -1); ties CERTIFIED and REFUSED (equal transverse speeds = structural corner re-alignment, found by the machine, dissolved by incommensurate integer speeds)

echo "=== SQRT-SUM-SIGN KAT gate: PASS=$pass FAIL=$fail ==="
[[ "$fail" == 0 ]] && exit 0 || exit 1
