#!/usr/bin/env python3
"""Generate _rm1_hv.iiifrag with HV-static byte constants and emitter fns.

Mirrors cg_rm1.c emit_bare_metal_entry, emit_vmx_svm_dispatch,
emit_svm_vmrun_bracket, emit_vmx_vmrun_bracket, emit_slat_tables,
emit_vmexit_dispatch_table, and the trailing BSS/.data sections from
iii_cg_rm1_emit_module.
"""

# Each blob: (name, asm-text-with-trailing-newlines)
BLOBS = {
"BARE_METAL_ENTRY": """\
    .text
    .global iii_hv_entry
iii_hv_entry:
    # D2 stack-pointer setup; D10 deterministic .align
    .align 16, 0x90
    leaq __iii_hv_stack_top(%rip), %rsp
    xorq %rbp, %rbp
    cld
    jmp  iii_hv_main
""",
"VMX_SVM_DISPATCH": """\
    .text
    .global iii_hv_vmx_svm_dispatch
iii_hv_vmx_svm_dispatch:
    # D3 CPUID(1).ECX[5] = VMX (Intel SDM Vol.2A CPUID)
    movl $1, %eax
    xorl %ecx, %ecx
    cpuid
    btl  $5, %ecx
    jc   iii_hv_path_vmx
    # D3 CPUID(0x80000001).ECX[2] = SVM (AMD APM Vol.3 §3.3)
    movl $0x80000001, %eax
    xorl %ecx, %ecx
    cpuid
    btl  $2, %ecx
    jc   iii_hv_path_svm
    # Neither VMX nor SVM available — halt.
    cli
iii_hv_dispatch_halt:
    hlt
    jmp  iii_hv_dispatch_halt
""",
"SVM_VMRUN_BRACKET": """\
    .text
    .global iii_hv_svm_vmrun_bracket
iii_hv_svm_vmrun_bracket:
    # D12 AMD APM Vol.3 §15.5 — clgi;vmload;vmrun;vmsave;stgi
    # rdi = phys addr of host VMCB save, rsi = phys addr of guest VMCB
    pushq %rbx
    movq  %rdi, %rbx     # host  VMCB phys
    movq  %rsi, %rax     # guest VMCB phys
    clgi
    vmload %rbx           # host save area
    vmrun  %rax           # enter guest
    vmsave %rbx           # host save area
    stgi
    popq  %rbx
    retq
""",
"VMX_VMRUN_BRACKET": """\
    .text
    .global iii_hv_vmx_vmrun_bracket
iii_hv_vmx_vmrun_bracket:
    # D13 Intel SDM Vol.3 §26.1 — VMLAUNCH on first entry, VMRESUME after
    # Per-VCPU launched flag at __iii_hv_vcpu_launched (1 byte/VCPU).
    # rdi = VCPU index.
    leaq __iii_hv_vcpu_launched(%rip), %rax
    movb (%rax,%rdi,1), %cl
    testb %cl, %cl
    jne  iii_hv_vmx_do_resume
    movb $1, (%rax,%rdi,1)
    vmlaunch
    jmp  iii_hv_vmx_post
iii_hv_vmx_do_resume:
    vmresume
iii_hv_vmx_post:
    retq
""",
"SLAT_HDR": """\
    .section .rodata.iii_hv_slat,"a",@progbits
    .align 4096, 0
iii_hv_slat_pml4:
    .quad iii_hv_slat_pdpt + 0x07
    .fill 511, 8, 0
    .align 4096, 0
iii_hv_slat_pdpt:
    .quad iii_hv_slat_pd0 + 0x07
    .quad iii_hv_slat_pd1 + 0x07
    .quad iii_hv_slat_pd2 + 0x07
    .quad iii_hv_slat_pd3 + 0x07
    .fill 508, 8, 0
""",
"VMEXIT_TBL_HDR": """\
    .section .rodata.iii_hv_vmexit_table,"a",@progbits
    .align 16, 0
    .global iii_hv_vmexit_table
iii_hv_vmexit_table:
""",
"VMEXIT_DEFAULT_LINE": """\
    .quad iii_hv_vmexit_default
""",
"BSS_HEAD": """\
    .section .bss.iii_hv,"aw",@nobits
    .align 4096, 0
    .global __iii_hv_stack_bottom
__iii_hv_stack_bottom:
    .skip 16384
    .global __iii_hv_stack_top
__iii_hv_stack_top:
    .align 64, 0
    .global __iii_hv_witness_ring
__iii_hv_witness_ring:
    .skip 32768
    .global __iii_hv_witness_ring_end
__iii_hv_witness_ring_end:
    .align 64, 0
    .global __iii_hv_vcpu_launched
__iii_hv_vcpu_launched:
    .skip 256
    .section .data.iii_hv,"aw",@progbits
    .align 8, 0
    .global __iii_hv_canary_seed
__iii_hv_canary_seed:
    .quad 0x3141592653589793
    .text
    .global __iii_hv_canary_fail
__iii_hv_canary_fail:
    cli
1:  hlt
    jmp 1b
    .global iii_hv_vmexit_default
iii_hv_vmexit_default:
    cli
1:  hlt
    jmp 1b
""",
"PD_ALIGN": "    .align 4096, 0\n",
"PD0_LBL": "iii_hv_slat_pd0:\n",
"PD1_LBL": "iii_hv_slat_pd1:\n",
"PD2_LBL": "iii_hv_slat_pd2:\n",
"PD3_LBL": "iii_hv_slat_pd3:\n",
"QUAD_OPEN": "    .quad 0x",
"NL": "\n",
"HDR1": "# III Stage-0 Ring -1 codegen output (iiis-0 freestanding HV)\n",
"HDR2": "# SysV AMD64 ABI; bare-metal; no host CRT.\n",
"ATTSYNTAX": "    .att_syntax\n",
"RODATA": "    .section .rodata\n",
"TRAILER_PFX": "# III_CG_RM1_ASM_SHA256: ",
}

def to_byte_array(name, text):
    bs = text.encode('utf-8')
    parts = [f"{b}u8" for b in bs]
    body = ", ".join(parts)
    return (f"var RM1_HV_{name} : [u8; {len(bs)}] = [{body}]\n"
            f"const RM1_HV_{name}_LEN: u64 = {len(bs)}u64\n")

def main():
    out = []
    out.append("/* AUTOGENERATED by _gen_rm1_hv.py — do not edit by hand.\n")
    out.append(" * HV-static byte constants for cg_rm1.iii Ring-1 codegen.\n */\n\n")
    for name, text in BLOBS.items():
        out.append(to_byte_array(name, text))
    out.append("\n")
    # Emit function: rm1_hv_emit_blob(addr,len) is just rm1_cg_emit_arr; use directly.
    # Bare-metal entry / dispatch / brackets: trivial wrappers.
    for name in ["BARE_METAL_ENTRY","VMX_SVM_DISPATCH","SVM_VMRUN_BRACKET","VMX_VMRUN_BRACKET"]:
        fn = name.lower()
        out.append(f"fn rm1_hv_emit_{fn}() -> u32 {{ return rm1_cg_emit_arr(&RM1_HV_{name} as u64, RM1_HV_{name}_LEN) }}\n")
    # SLAT: header + 4 PD blocks each 512 entries
    out.append("""\
fn rm1_hv_emit_one_pd(g: u32) -> u32 {
    rm1_cg_emit_arr(&RM1_HV_PD_ALIGN as u64, RM1_HV_PD_ALIGN_LEN)
    if g == 0u32 { rm1_cg_emit_arr(&RM1_HV_PD0_LBL as u64, RM1_HV_PD0_LBL_LEN) }
    else { if g == 1u32 { rm1_cg_emit_arr(&RM1_HV_PD1_LBL as u64, RM1_HV_PD1_LBL_LEN) }
    else { if g == 2u32 { rm1_cg_emit_arr(&RM1_HV_PD2_LBL as u64, RM1_HV_PD2_LBL_LEN) }
    else { rm1_cg_emit_arr(&RM1_HV_PD3_LBL as u64, RM1_HV_PD3_LBL_LEN) } } }
    let g64: u64 = g as u64
    let mut e: u32 = 0u32
    while e < 512u32 {
        let phys: u64 = (g64 << 30u64) | ((e as u64) << 21u64)
        let val: u64 = phys | 0xB7u64
        rm1_cg_emit_arr(&RM1_HV_QUAD_OPEN as u64, RM1_HV_QUAD_OPEN_LEN)
        rm1_cg_emit_hex(val)
        rm1_cg_emit_arr(&RM1_HV_NL as u64, RM1_HV_NL_LEN)
        e = e + 1u32
    }
    return RM1_OK
}
fn rm1_hv_emit_slat_tables() -> u32 {
    rm1_cg_emit_arr(&RM1_HV_SLAT_HDR as u64, RM1_HV_SLAT_HDR_LEN)
    let mut g: u32 = 0u32
    while g < 4u32 { rm1_hv_emit_one_pd(g); g = g + 1u32 }
    return RM1_OK
}
fn rm1_hv_emit_vmexit_table() -> u32 {
    rm1_cg_emit_arr(&RM1_HV_VMEXIT_TBL_HDR as u64, RM1_HV_VMEXIT_TBL_HDR_LEN)
    let mut i: u32 = 0u32
    while i < 256u32 {
        rm1_cg_emit_arr(&RM1_HV_VMEXIT_DEFAULT_LINE as u64, RM1_HV_VMEXIT_DEFAULT_LINE_LEN)
        i = i + 1u32
    }
    return RM1_OK
}
fn rm1_hv_emit_bss_and_data() -> u32 {
    return rm1_cg_emit_arr(&RM1_HV_BSS_HEAD as u64, RM1_HV_BSS_HEAD_LEN)
}
""")
    with open('_rm1_hv.iiifrag','w',encoding='utf-8',newline='\n') as f:
        f.write(''.join(out))
    print("wrote _rm1_hv.iiifrag")

if __name__ == "__main__": main()
