#!/usr/bin/env python3
"""Generate cg_rm2 .iii string-table var declarations.

Outputs to stdout.  Each declaration is:

    var <NAME>     : [u8; <LEN>] = [b0u8, b1u8, ...]
    const <NAME>_LEN : u64 = <LEN>u64

so the .iii body can call cgrm2_emit_bytes(&NAME as u64, NAME_LEN).
This keeps every fixed-string emit path NUL-free and length-known.
"""
import sys

STRS = [
    ("SEC_TEXT_PE",     "    .section .xii_sanctum.text, \"xr\"\n"),
    ("SEC_TEXT_ELF",    "    .section .xii_sanctum.text, \"ax\", @progbits\n"),
    ("SEC_RODATA_PE",   "    .section .xii_sanctum.rodata, \"r\"\n"),
    ("SEC_RODATA_ELF", "    .section .xii_sanctum.rodata, \"a\", @progbits\n"),
    ("PFX_LSANCTUM",    "L_sanctum_"),
    ("PFX_IIISANCTUM", "iii_sanctum_"),
    ("PFX_XIISANCTUM", "xii_sanctum_"),
    ("PFX_IIICAP",      "iii_cap_"),
    ("SYM_ONEWAY",      "iii_sanctum_oneway_port"),
    ("SYM_CAPREVOKE",   "iii_cap_revoke"),
    ("STR_LEAQ",        "    leaq "),
    ("STR_RIPCM_PCT",   "(%rip), %"),
    ("STR_MOVQ_LD",     "    movq "),
    ("STR_MOVQ_PRAX_C", "    movq %rax, "),
    ("STR_MOVQ_PCT",    "    movq %"),
    ("STR_COMMA_SP",    ", "),
    ("STR_RIP_PAREN",   "(%rip)\n"),
    ("STR_PFX_STR",         "L_sanctum_str_"),
    ("STR_PFX_MHASH",       "L_sanctum_mhash_"),
    ("STR_PFX_FORTOP",      "L_sanctum_for_top_"),
    ("STR_PFX_FOREND",      "L_sanctum_for_end_"),
    ("STR_PFX_FORCONT",     "L_sanctum_for_continue_"),
    ("STR_PFX_MATCHEND",    "L_sanctum_match_end_"),
    ("STR_PFX_SKIP",        "L_sanctum_skip_"),
    ("STR_HDR1",        "# III Stage-0 Ring -2 codegen output (SANCTUM-sealed)\n"),
    ("STR_HDR2",        "# Spec: SPEC.XII S14 + DRTM (Intel TXT MLE / TCG D-RTM 1.0).\n"),
    ("STR_ATTSYNTAX",   "    .att_syntax\n"),
    ("STR_BAL32",       "    .balign 32\n"),
    ("STR_BAL16",       "    .balign 16\n"),
    ("STR_BAL8",        "    .balign 8\n"),
    ("STR_GLOBAL",      "    .global "),
    ("STR_TYPE",        "    .type "),
    ("STR_TYPEFUNC",    ", @function\n"),
    ("STR_SIZE",        "    .size "),
    ("STR_DOTMINUS",    ", .-"),
    ("STR_NL",          "\n"),
    ("STR_COLONNL",     ":\n"),
    ("STR_GLOBAL_MHPL", "    .global iii_sanctum_mhash_placeholder\n"),
    ("STR_MHPL_LBL",    "iii_sanctum_mhash_placeholder:\n"),
    ("STR_MHPL_CMT",    "    /* D3: 32-byte zero blob; linker patches with section mhash. */\n"),
    ("STR_MHPL_ZERO",   "    .byte 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0\n"),
    ("STR_BYTE",        "    .byte "),
    ("STR_PROLOG",      "    pushq %rbp\n    pushq %r15\n    pushq %r14\n    pushq %r13\n    pushq %r12\n    pushq %rbx\n"),
    ("STR_MOVRSPRBP",   "    movq %rsp, %rbp\n    subq $1024, %rsp\n"),
    ("STR_FRAMEZ",      "    /* D12: zero local frame (1024 bytes) */\n    movq %rsp, %rdi\n    xorq %rax, %rax\n    movq $128, %rcx\n    rep stosq\n"),
    ("STR_CAPV",        "    /* D10: cap-handle verify */\n    movq -8(%rbp), %rdi\n    callq iii_cap_verify\n"),
    ("STR_EPILOGUE",    "    movq %rbp, %rsp\n    popq %rbx\n    popq %r12\n    popq %r13\n    popq %r14\n    popq %r15\n    popq %rbp\n    retq\n"),
    ("STR_VOLCLEAR",    "    xorq %rcx, %rcx\n    xorq %rdx, %rdx\n    xorq %rsi, %rsi\n    xorq %rdi, %rdi\n    xorq %r8,  %r8\n    xorq %r9,  %r9\n    xorq %r10, %r10\n    xorq %r11, %r11\n"),
    ("STR_PXOR",        "    pxor %xmm"),
    ("STR_PXOR_COMMA",  ", %xmm"),
    ("STR_XORRAX",      "    xorq %rax, %rax\n"),
    ("STR_PUSHRAX",     "    pushq %rax\n"),
    ("STR_POPRAX",      "    popq %rax\n"),
    ("STR_POPRCX",      "    popq %rcx\n"),
    ("STR_POPRDX",      "    popq %rdx\n"),
    ("STR_POPRDI",      "    popq %rdi\n"),
    ("STR_POPRSI",      "    popq %rsi\n"),
    ("STR_POPR8",       "    popq %r8\n"),
    ("STR_POPR9",       "    popq %r9\n"),
    ("REG_RDI",         "rdi"),
    ("REG_RSI",         "rsi"),
    ("REG_RDX",         "rdx"),
    ("REG_RCX",         "rcx"),
    ("REG_R8",          "r8"),
    ("REG_R9",          "r9"),
    ("REG_RAX",         "rax"),
    ("STR_MOVABSQ_OPEN","    movabsq $0x"),
    ("STR_COMMA_RAX_NL",", %rax\n"),
    ("STR_COMMA_RCX_NL",", %rcx\n"),
    ("STR_DOL_DASH",    ", -"),
    ("STR_PCT_RBP_NL",  "(%rbp)\n"),
    ("STR_DASH_OPEN",   "    movq -"),
    ("STR_BPCMA_RAX",   "(%rbp), %rax\n"),
    ("STR_BPCMA_RCX",   "(%rbp), %rcx\n"),
    ("STR_ADDQ",        "    addq %rcx, %rax\n"),
    ("STR_SUBQ",        "    subq %rcx, %rax\n"),
    ("STR_IMULQ",       "    imulq %rcx, %rax\n"),
    ("STR_IDIV",        "    cqto\n    idivq %rcx\n"),
    ("STR_IDIVMOD",     "    cqto\n    idivq %rcx\n    movq %rdx, %rax\n"),
    ("STR_ANDQ",        "    andq %rcx, %rax\n"),
    ("STR_ORQ",         "    orq %rcx, %rax\n"),
    ("STR_XORQ",        "    xorq %rcx, %rax\n"),
    ("STR_SHLQ",        "    shlq %cl, %rax\n"),
    ("STR_SHRQ",        "    shrq %cl, %rax\n"),
    ("STR_NEGQ",        "    negq %rax\n"),
    ("STR_NOTQ",        "    notq %rax\n"),
    ("STR_DEREF_RAX",   "    movq (%rax), %rax\n"),
    ("STR_TESTRSTNE",   "    testq %rax, %rax\n    setne %al\n    movzbq %al, %rax\n"),
    ("STR_TESTRSTE",    "    testq %rax, %rax\n    sete %al\n    movzbq %al, %rax\n"),
    ("STR_LAND_P1",     "    testq %rax, %rax\n    setne %al\n    movzbq %al, %rdx\n"),
    ("STR_LAND_P2",     "    testq %rcx, %rcx\n    setne %al\n    movzbq %al, %rax\n"),
    ("STR_LAND_AND",    "    andq %rdx, %rax\n"),
    ("STR_LOR_LINE",    "    orq %rcx, %rax\n    testq %rax, %rax\n    setne %al\n    movzbq %al, %rax\n"),
    ("STR_CMP_RCX_RAX", "    cmpq %rcx, %rax\n"),
    ("STR_SETE",        "    sete %al\n    movzbq %al, %rax\n"),
    ("STR_SETNE",       "    setne %al\n    movzbq %al, %rax\n"),
    ("STR_SETL",        "    setl %al\n    movzbq %al, %rax\n"),
    ("STR_SETLE",       "    setle %al\n    movzbq %al, %rax\n"),
    ("STR_SETG",        "    setg %al\n    movzbq %al, %rax\n"),
    ("STR_SETGE",       "    setge %al\n    movzbq %al, %rax\n"),
    ("STR_INDEX_LD",    "    movq (%rax,%rcx,8), %rax\n"),
    ("STR_INDEX_ST",    "    movq %rdx, (%rax,%rcx,8)\n"),
    ("STR_CALLQ",       "    callq "),
    ("STR_CALL_INDIR",  "    callq *%rax\n"),
    ("STR_SUB8RSP",     "    subq $8, %rsp\n"),
    ("STR_ADD8RSP",     "    addq $8, %rsp\n"),
    ("STR_MOVQRAX_DASH","    movq %rax, -"),
    ("STR_JMP_SP",      "    jmp "),
    ("STR_JNE_SP",      "    jne "),
    ("STR_JZ_SP",       "    jz "),
    ("STR_JGE_SP",      "    jge "),
    ("STR_MOVQ0RAX",    "    movq $0, %rax\n"),
    ("STR_MOVQ1RAX",    "    movq $1, %rax\n"),
    ("STR_DOL_0_DASH",  "    movq $0, -"),
    ("STR_ADD1RAX",     "    addq $1, %rax\n"),
    ("ENAME_OK",                 "OK"),
    ("ENAME_NULL_ARG",           "NULL_ARG"),
    ("ENAME_IO",                 "IO"),
    ("ENAME_UNSUPPORTED",        "UNSUPPORTED"),
    ("ENAME_NON_PIC_RELOC",      "NON_PIC_RELOC"),
    ("ENAME_FORBIDDEN_TARGET",   "FORBIDDEN_TARGET"),
    ("ENAME_BAD_ENTRY_SIG",      "BAD_ENTRY_SIG"),
    ("ENAME_ONEWAY_READ",        "ONEWAY_READ"),
    ("ENAME_NO_CAP_REVOKE",      "NO_CAP_REVOKE"),
    ("ENAME_SEALED",             "SEALED"),
    ("ENAME_INTERNAL",           "INTERNAL"),
    ("ENAME_UNKNOWN",            "<unknown>"),
]

def emit():
    out = []
    for name, s in STRS:
        b = s.encode("utf-8")
        n = len(b)
        bytes_str = ", ".join(f"{x}u8" for x in b)
        out.append(f"var {name} : [u8; {n}] = [{bytes_str}]")
        out.append(f"const {name}_LEN : u64 = {n}u64")
    return "\n".join(out) + "\n"

if __name__ == "__main__":
    sys.stdout.write(emit())
